-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 06:29:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shopsandcoupons
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shopsandcoupons` ;

-- -----------------------------------------------------
-- Schema shopsandcoupons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopsandcoupons` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `shopsandcoupons` ;

-- -----------------------------------------------------
-- Table `shopsandcoupons`.`coupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopsandcoupons`.`coupons` ;

CREATE TABLE IF NOT EXISTS `shopsandcoupons`.`coupons` (
  `coupon_id` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NULL DEFAULT NULL,
  `desc` MEDIUMTEXT NULL DEFAULT NULL,
  `img_src` TINYTEXT NOT NULL,
  `times` VARCHAR(45) NOT NULL,
  `shop_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`coupon_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopsandcoupons`.`shops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopsandcoupons`.`shops` ;

CREATE TABLE IF NOT EXISTS `shopsandcoupons`.`shops` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `site` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shop_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1151
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
